---
- hosts: all
  gather_facts: false
  #ignore_errors: true
  tasks:
    - name: Check the date
      command: date
      ignore_errors: yes
    - name: Check the uptime
      command: |
        uptime
        nproc
        date

- hosts: ws
  tasks: 
    - name: Check the cpu
      command: lscpu
